// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFC6vYw1VkIg0sVQE-KGg0Cf7-Tdlb1rs',
    appId: '1:1096528072060:web:11d0b259e227a1e4fc28f9',
    messagingSenderId: '1096528072060',
    projectId: 'tp2i-2e6da',
    authDomain: 'tp2i-2e6da.firebaseapp.com',
    storageBucket: 'tp2i-2e6da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwO0gzKPTFI34N0xoOhbx8DA9-gABzBkU',
    appId: '1:1096528072060:android:943d98d5df886a34fc28f9',
    messagingSenderId: '1096528072060',
    projectId: 'tp2i-2e6da',
    storageBucket: 'tp2i-2e6da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0K5r5WYPCrOEbMaFOnqrHBN9oZX1zwYE',
    appId: '1:1096528072060:ios:981637ed07a72332fc28f9',
    messagingSenderId: '1096528072060',
    projectId: 'tp2i-2e6da',
    storageBucket: 'tp2i-2e6da.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0K5r5WYPCrOEbMaFOnqrHBN9oZX1zwYE',
    appId: '1:1096528072060:ios:981637ed07a72332fc28f9',
    messagingSenderId: '1096528072060',
    projectId: 'tp2i-2e6da',
    storageBucket: 'tp2i-2e6da.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFC6vYw1VkIg0sVQE-KGg0Cf7-Tdlb1rs',
    appId: '1:1096528072060:web:9fb2f601d5e925c6fc28f9',
    messagingSenderId: '1096528072060',
    projectId: 'tp2i-2e6da',
    authDomain: 'tp2i-2e6da.firebaseapp.com',
    storageBucket: 'tp2i-2e6da.firebasestorage.app',
  );
}
